### configuration.yaml
homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: 75
  unit_system: metric
  time_zone: Australia/Sydney
  customize: !include includes/customize.yaml

##logger:

http:
  api_password: !secret http_api_password

#climate:
#  platform: fan
fan:
  platform: dyson

vera:
  vera_controller_url: !secret vera_url
  lights: [2, 3, 4, 6, 7, 8, 9, 13, 15, 16, 17, 18, 21, 24, 25, 26, 28, 29, 30, 31, 33]

mqtt:
  broker: !secret mqtt_ip
  port: !secret mqtt_port
  username: !secret mqtt_uname
  password: !secret mqtt_pass
  discovery: true
  discovery_prefix: home

doorbird:
  host: !secret doorbird_url
  username: !secret doorbird_uname
  password: !secret doorbird_pass
  doorbell_events: true

dyson:
  username: !secret dyson_uname
  password: !secret dyson_pass
  language: AU
  devices:
    - device_id: !secret dyson_dev_id1
      device_ip: !secret dyson_ip1

notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api_key

google:
  client_id: !secret google_id
  client_secret: !secret google_secret

device_tracker:
#  - platform: owntracks
#  - platform: tile
#    username: tile_uname
#    password: tile_pass

## Includes
group: !include includes/groups.yaml
scene: !include includes/scenes.yaml
sensor: !include includes/sensors.yaml
zone: !include includes/zones.yaml
switch: !include includes/switch.yaml
binary_sensor: !include includes/binary_sensor.yaml
input_select: !include includes/input_select.yaml
input_number: !include includes/input_number.yaml
input_boolean: !include includes/input_boolean.yaml
camera: !include includes/camera.yaml

## Dir Includes
automation: !include_dir_merge_list automation
script: !include_dir_merge_named scripts

## Activations
recorder:
  purge_interval: 2
  purge_keep_days: 5
  exclude:
    domains:
      - automation
      - updater
    entities:
      - sun.sun # Don't record sun data
      - sensor.last_boot # Comes from 'systemmonitor' sensor platform
      - sensor.date

updater:
discovery:
apcupsd:
conversation:
sun:
tts:
  platform: google
ios:
frontend:
history:
logbook:

#cloud:
#config:

## emulated_hue:
##  type: alexa
##  listen_port: 8300
##  exposed domains:
##    - light
##    - switch
##    - script

#ifttt:
#  key: xxxxx-x-xxxxxxxxxxxxx

# Weather Prediction
#sensor:
#  platform: yr
####################
