### configuration.yaml #
homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: 75
  unit_system: metric
  time_zone: Australia/Sydney
  whitelist_external_dirs:
    - /home/homeassistant/.homeassistant/
  customize: !include includes/customize.yaml

##logger:

http:
  api_password: !secret http_api_password
  ssl_certificate: !secret ssl_certificate_loc
  ssl_key: !secret ssl_key_loc
  base_url: !secret base_url

fan:
  platform: dyson

vera:
  vera_controller_url: !secret vera_url
  lights: [2, 3, 4, 6, 7, 8, 9, 13, 15, 16, 17, 18, 21, 24, 25, 26, 28, 29, 30, 31, 33]

mqtt:
  broker: !secret mqtt_ip
  port: !secret mqtt_port
  username: !secret mqtt_uname
  password: !secret mqtt_pass
  discovery: true
  discovery_prefix: home

doorbird:
  host: !secret doorbird_host
  username: !secret doorbird_uname
  password: !secret doorbird_pass
  doorbell_events: true
  hass_url_override: !secret doorbird_hass_url_override

dyson:
  username: !secret dyson_uname
  password: !secret dyson_pass
  language: AU
  devices:
    - device_id: !secret dyson_dev_id1
      device_ip: !secret dyson_ip1

bmw_connected_drive:
  bmw_x5:
    username: !secret USERNAME_BMW_CONNECTED_DRIVE
    password: !secret PASSWORD_BMW_CONNECTED_DRIVE
    region: rest_of_world
#    country: Australia

notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api_key

google:
  client_id: !secret google_id
  client_secret: !secret google_secret

device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200
    waypoints: False
    events_only: True
    mqtt_topic: "owntracks/#"

#  - platform: asuswrt
#    host: !secret AP_IP
#    username: !secret AP_ADMIN_USERNAME
#    password: !secret AP_ADMIN_PASS
#    mode: ap
#    require_ip: false
#    new_device_defaults:
#      track_new_devices: false
#      hide_if_away: false

#  - platform: tile
#    username: tile_uname
#    password: tile_pass

## Includes
group: !include includes/groups.yaml
scene: !include includes/scenes.yaml
sensor: !include includes/sensors.yaml
zone: !include includes/zones.yaml
switch: !include includes/switch.yaml
binary_sensor: !include includes/binary_sensor.yaml
input_select: !include includes/input_select.yaml
input_number: !include includes/input_number.yaml
input_boolean: !include includes/input_boolean.yaml
camera: !include includes/camera.yaml
ios: !include includes/ios.yaml

## Dir Includes
automation: !include_dir_merge_list automation
script: !include_dir_merge_named scripts

## Activations
frontend:
  themes: !include_dir_merge_named themes/

recorder:
  purge_interval: 2
  purge_keep_days: 7
  include:
    domains:
      - switch
      - device_tracker
      - light
      - sun
      - input_boolean
      - input_number
      - input_select
      - binary_sensor
      - sensor
      - switch
      - media_player
  exclude:
    domains:
      - updater
    entities:
      - sun.sun # Don't record sun data
      - sensor.date

logbook:
  include:
    domains:
      - switch
      - device_tracker
      - light
      - input_number
      - input_select
      - script
    entities:
      - sun.sun
  exclude:
    domains:
      - sensor
      - media_player

updater:
discovery:
apcupsd:
conversation:
sun:
tts:
  platform: google
history:


#cloud:
#config:

#climate:
#  platform: fan

## emulated_hue:
##  type: alexa
##  listen_port: 8300
##  exposed domains:
##    - light
##    - switch
##    - script

#ifttt:
#  key: xxxxx-x-xxxxxxxxxxxxx

# Weather Prediction
#sensor:
#  platform: yr
####################
