## Doorbird.yaml automation
- alias: Doorbird ring
  trigger:
    platform: event
    event_type: doorbird_doorbell
  action:
    service: script.turn_on
    data_template:
      entity_id: >
        {% if states.input_select.house_mode.state == 'Bedtime' %}
          script.doorbell_night
        {% elif states.input_select.house_mode.state == 'Night' %}
          script.doorbell_night
        {% else %}
          script.doorbell
        {% endif %}

- alias: Doorbird ring lights
  trigger:
    platform: event
    event_type: doorbird_doorbell
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.house_mode
        state: 'Evening'
      - condition: state
        entity_id: input_select.house_mode
        state: 'Night'
      - condition: state
        entity_id: input_select.house_mode
        state: 'Holiday'
      - condition: state
        entity_id: input_select.house_mode
        state: 'Bedtime'
  action:
    - service: light.turn_on
      entity_id:
        - light.front_porch_21
        - light.front_garden_28
    - service: script.turn_off #turn off any currently running timers
      entity_id: script.doorbell_lights_off
    - delay: '00:03:00'
    - service: script.turn_on
      entity_id: script.doorbell_lights_off # start a new timer

- alias: Sonos Doorbell Test
  trigger:
    platform: state
    entity_id: input_boolean.sonos_test
    to: 'on'
  action:
    service: script.turn_on
    data:
      entity_id: script.sonos_group_test
