## Doorbird
- alias: Doorbird ring
  trigger:
  - platform: event
    event_type: doorbird_doorbell
  action:
    - service: script.turn_on
      data_template:
        entity_id: >
          {% if states.input_select.house_mode.state == 'Bedtime' %}
            script.doorbell_night
          {% elif states.input_select.house_mode.state == 'Night' %}
            script.doorbell_night
          {% else %}
            script.doorbell
          {% endif %}

- alias: Sonos Test
  trigger:
  - platform: state
    entity_id: input_boolean.sonos_test
    to: 'on'
  action:
    - service: script.turn_on
      data:
        entity_id: script.sonos_goup_test
