## Doorbird.yaml automation
- alias: Doorbird ring
  trigger:
    platform: event
    event_type: doorbird_front_gate_button
  action:
    - service: logbook.log
      data:
        name: "Doorbird:"
        message: Front gate button pushed
    - service: script.turn_off
      data:
        entity_id:
          - script.doorbell
          - script.doorbell_night
    - service: script.turn_on
      data_template:
        entity_id: >
          {% if is_state('input_select.house_mode', 'Bedtime') or is_state('input_select.house_mode', 'Night') %}
            script.doorbell_night
          {% elif states.input_boolean.evening_holiday.state == 'on' %}
            script.doorbell_night
          {% else %}
            script.doorbell
          {% endif %}

- alias: Doorbird ring lights
  trigger:
    platform: event
    event_type: doorbird_front_gate_button
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.house_mode
        state: 'Evening'
      - condition: state
        entity_id: input_select.house_mode
        state: 'Night'
      - condition: state
        entity_id: input_boolean.evening_holiday
        state: 'on'
      - condition: state
        entity_id: input_select.house_mode
        state: 'Bedtime'
  action:
    - delay:
        seconds: 2
    - service: light.turn_on
      entity_id:
        - switch.front_porch_switch
        - switch.front_garden_1_switch
    - service: logbook.log
      data:
        name: "Lights:"
        message: Doorbell lights activated
    - service: script.turn_off
      entity_id: script.timer_front_lights_off
    - service: script.turn_on
      entity_id: script.timer_front_lights_off

- alias: Sonos Doorbell Test
  trigger:
    platform: state
    entity_id: input_boolean.doorbell_test
    to: 'on'
  action:
    - event: doorbird_front_gate_button
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.doorbell_test


#    service: script.turn_on
#    data:
#      entity_id: script.sonos_group_test
