## general.yaml automations

- alias: HA Update notification
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.ios_darren
    data_template:
      title: 'New Home Assistant Release'
      message: "Home Assistant  {{ states.updater.updater.state }}  is now available."

- alias: Front Door Open
  trigger:
    - platform: state
      entity_id: input_select.house_mode
      to: 'Bedtime'
    - platform: state
      entity_id: input_select.house_mode
      to: 'Night'
  condition:
    condition: state
    entity_id: binary_sensor.front_door_sensor
    state: 'on'
  action:
    service: notify.ios_darren
    data:
      message: "Front Door Still OPEN!"

## Auto change themes
- alias: hass_theme
  trigger:
    - platform: state
      entity_id: input_select.hass_theme
  action:
    - service: frontend.set_theme
      data_template:
        name: "{{ states.input_select.hass_theme.state }}"
