## lights.yaml automation

## Kitchen motion
#- alias: "Kitchen Motion ON"
#  trigger:
#    platform: state
#    entity_id: binary_sensor.kitchen_sensor_46
#    to: 'on'
## this should work to replace the motion detection logic, but will runn every single time motion is triggered 24x7
#  action:
#    service: script.turn_on
#    data_template:
#      entity_id: >
#        {% if states.input_select.house_mode.state == 'Day' and states.sensor.light_sensor_61.state > '20' and states.input_boolean.morning_lights_flag.state == 'off' %}
#          script.morning_lights_on
#        {% elif states.input_select.house_mode.state == 'Holiday' %}
#          script.alarm
#        {% endif %}

## Kitchen Morning Motion light on
- alias: "Kitchen Morning Lights sensor ON"
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_sensor_46
    to: 'on'
  condition:
# add or condition - if Holiday - send notify to mobile otherwise do below
    - condition: state
      entity_id: input_select.house_mode
      state: 'Day'
    - condition: state
      entity_id: input_boolean.morning_lights_flag
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.light_sensor_61 # this updates fom the Z-wave sensor every 8mins?
      below: 50
  action:
    - service: logbook.log
      data_template:
        name: Kitchen
        message: motion detected
        entity_id: binary_sensor.kitchen_sensor_46
        domain: binary_sensor
    - service: script.turn_on
      entity_id: script.morning_lights_on

## Kitchen Morning Light sensor lights off
- alias: "Morning lights sensor OFF"
  trigger:
    platform: numeric_state
    entity_id: sensor.light_sensor_61 # this updates fom the Z-wave sensor every 8mins?
    above: 50
#    for:
#      minutes: 10
  action:
    - service: script.turn_on
      entity_id: script.morning_lights_off

- alias: "Morning Lights manual ON"
  trigger:
    platform: state
    entity_id: input_boolean.morning_lights
    to: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.morning

- alias: "Morning Lights manual OFF"
  trigger:
    platform: state
    entity_id: input_boolean.morning_lights
    to: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.morning_off

- alias: Bedtime switch on
  trigger:
    platform: state
    entity_id: input_boolean.bed_time
    to: 'on'
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.house_mode
      option: 'Bedtime'
#    - service: script.turn_on
#      data:
#        entity_id: script.bedtime

- alias: Arrive_home_evening
  trigger:
    platform: state
    entity_id: input_boolean.darrenhome, input_boolean.blythehome
    to: 'on'
  condition:
    condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
    - service: light.turn_on
      entity_id:
        light.front_porch_21
    - service: script.turn_on
      entity_id: script.timer_front_lights_off

- alias: Bedtime switch off # if triggered manually while the timer is running will turn the stairs light off early
  trigger:
    platform: state
    entity_id: input_boolean.bed_time
    to: 'off'
  action:
    service: light.turn_off
    entity_id: light.stairs_16

- alias: "Holiday Evening Light"
  trigger:
    platform: state
    entity_id: input_boolean.evening_holiday
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.front_garden_28

## Dimmers
#- alias: Kitchen High Dimmer
#  trigger:
#    platform: state
#    entity_id: input_number.kitchen_high_dimmer
#  action:
#    service: light.turn_off
#    entity_id: light.stairs_16

## Hall Night Motion
#- alias: "Hall motion sensor ON"
#  trigger:
#    - platform: state
#      entity_id: binary_sensor.hall_sensor_50
#      from: 'off'
#      to: 'on'
#  condition:
#    - condition: state
#      entity_id: input_select.house_mode
#      state: 'Night'
#  action:
#    - service: light.turn_on
#      entity_id: light.tv_4
#      data:
#        brightness: 30
#Turn off Hall light 2 minutes after last movement
#- alias: "Hall motion sensor OFF"
#  trigger:
#    platform: state
#    entity_id: binary_sensor.hall_sensor_50
#    to: 'off'
#    for:
#      minutes: 5
#  condition:
#    condition: state
#    entity_id: input_select.house_mode
#    state: 'Night'
#  action:
#      service: light.turn_off
#      entity_id: light.tv_4
