## lights.yaml automation

## Kitchen Morning Motion light on
- alias: "Kitchen Morning Lights sensor ON"
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_sensor_46
    to: 'on'
  condition:
    - condition: state
      entity_id: input_select.house_mode
      state: 'Day'
    - condition: state
      entity_id: input_boolean.morning_lights_flag
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.light_sensor_61 # this updates fom the Z-wave sensor every 8mins?
      below: 20
  action:
    - service: script.turn_on
      entity_id: script.morning_lights_on
    - event: LOGBOOK_ENTRY
      event_data:
        name: Morning Lights
        message: Sensor turned on
        entity_id: light.kitchen_bench_7
        domain: light

## Kitchen Morning Light sensor lights off
- alias: "Morning lights sensor OFF"
  trigger:
    platform: numeric_state
    entity_id: sensor.light_sensor_61 # this updates fom the Z-wave sensor every 8mins?
    above: 20
#    for:
#      minutes: 10
  action:
    - service: script.turn_on
      entity_id: script.morning_off

- alias: "Morning Lights manual ON"
  trigger:
    platform: state
    entity_id: input_boolean.morning_lights
    to: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.morning

- alias: "Morning Lights manual OFF"
  trigger:
    platform: state
    entity_id: input_boolean.morning_lights
    to: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.morning_off

- alias: Bedtime switch on
  trigger:
    platform: state
    entity_id: input_boolean.bed_time
    to: 'on'
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.house_mode
      option: 'Bedtime'
#    - service: script.turn_on
#      data:
#        entity_id: script.bedtime

- alias: Bedtime switch off # if triggered manually while the timer is running will turn the stairs light off early
  trigger:
    platform: state
    entity_id: input_boolean.bed_time
    to: 'off'
  action:
    service: light.turn_off
    entity_id: light.stairs_16

## Hall Night Motion
#- alias: "Hall motion sensor ON"
#  trigger:
#    - platform: state
#      entity_id: binary_sensor.hall_sensor_50
#      from: 'off'
#      to: 'on'
#  condition:
#    - condition: state
#      entity_id: input_select.house_mode
#      state: 'Night'
#  action:
#    - service: light.turn_on
#      entity_id: light.tv_4
#      data:
#        brightness: 30
#Turn off Hall light 2 minutes after last movement
#- alias: "Hall motion sensor OFF"
#  trigger:
#    platform: state
#    entity_id: binary_sensor.hall_sensor_50
#    to: 'off'
#    for:
#      minutes: 5
#  condition:
#    condition: state
#    entity_id: input_select.house_mode
#    state: 'Night'
#  action:
#      service: light.turn_off
#      entity_id: light.tv_4
