# open_front_gate.yaml automation
- alias: "Open Front Gate"
  trigger:
    platform: state
    entity_id: input_boolean.open_front_gate
    to: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.front_gate_relay_1
    - delay:
        seconds: 3
    - service: input_boolean.turn_off
      entity_id: input_boolean.open_front_gate
