- alias: "Sydney FC Game Start"
  trigger:
    platform: state
    entity_id: input_boolean.sydneyfc_game
    to: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.sydneyfc

- alias: "Sydney FC Game End"
  trigger:
    platform: state
    entity_id: input_boolean.sydneyfc_game
    to: 'off'
  action:
    service: light.turn_off
    entity_id: light.lounge_lamp_3

##service template working test
- alias: "testing"
  trigger:
    platform: state
    entity_id: input_boolean.tester
    to: 'on'
  action:
    - service_template: >
        {% if states.device_tracker.reynolds_darren.state == 'study' %}
          light.turn_on
        {% endif %}
      entity_id: light.study_lamp_18
    - service: logbook.log
      data_template:
        name: test
        message: "on"
#        {% else %}
#          light.turn_off
#        entity_id: input_boolean.tester
