### tracked events automation - things happengin with beacons

- alias: Frontgate Darren
  trigger:
    platform: state
    entity_id: device_tracker.reynolds_darren
    to: frontgate
  action:
    service: switch.turn_on
    data:
      entity_id: switch.open_door

#    service: script.turn_on
#    data:
#      entity_id: script.open_front_gate

- alias: Frontgate Blythe
  trigger:
    platform: state
    entity_id: device_tracker.reynolds_blythe
    to: frontgate
  action:
    service: switch.turn_on
    data:
      entity_id: switch.open_door

- alias: Masterbed Beacon Goodnight
  trigger:
    platform: state
    entity_id: device_tracker.reynolds_darren
    to: masterbed
  condition:
    - condition: time
      after: '20:30:00'
    - condition: state
      entity_id: input_select.house_mode
      state: 'Evening'
    - condition: state
      entity_id: input_boolean.bedtime_beacon_flag
      state: 'off'
  action: # in future make this an actionable nofication to turn off lights
    service: notify.ios_Darren
    data:
      message: "Going to Bed? What do do with the lights?"
      data:
        push:
          badge: 5
          category: "bedtime_lights" # Needs to match the top level identifier you used in the ios configuration
#    - service: script.turn_on
#      data:
#        entity_id: script.bedtime

- alias: Bedtime Now
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: BEDTIME_NOW
  action:
    - service: script.turn_on
      data:
        entity_id: script.bedtime_now

- alias: Bedtime Delay
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: BEDTIME_DELAY
  action:
    - service: script.turn_on
      data:
        entity_id: script.bedtime
    - service: logbook.log
      data_template:
        name: Bedtime DELAY
        message: action selected
- alias: Bedtime Set Night
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: NIGHT
  action:
    - service: script.turn_on
      data:
        entity_id: script.night
    - service: logbook.log
      data_template:
        name: Bedtime NIGHT
        message: action selected

- alias: Morning Lights
  trigger:
    platform: state
    entity_id: device_tracker.reynolds_darren
    to: kitchen
  condition:
    - condition: state
      entity_id: input_boolean.morning_lights_flag
      state: 'off' #so this only happerns once in the morning
    - condition: time
      before: '07:30:00'
  action: # in future make this an actionable nofication?
    - service: script.turn_on
      entity_id: script.morning_lights

#- alias: Masterbed on
#  trigger:
#    platform: state
#    entity_id: device_tracker.reynolds_darren
#    to: masterbed
#  action:
#    service: light.turn_on
#    entity_id: light.study_31

#- alias: Masterbed off
#  trigger:
#    platform: state
#    entity_id: device_tracker.reynolds_darren
#    from: masterbed
#  action:
#    service: light.turn_off
#    entity_id: light.study_31

#- alias: Enter Front Door
#  trigger:
#    platform: zone
#    entity_id: device_tracker.reynolds_darren
#    zone: zone.FrontDoorBeacon
#    # Event is either enter or leave
#    event: enter
#  action:
#    service: light.turn_on
#    entity_id: light.hallway_5
