### tracked events
- alias: Frontgate Darren
  trigger:
    platform: state
    entity_id: device_tracker.reynolds_darren
    to: frontgate
  action:
    service: switch.turn_on
    data:
      entity_id: switch.open_door

#    service: script.turn_on
#    data:
#      entity_id: script.open_front_gate

- alias: Frontgate Blythe
  trigger:
    platform: state
    entity_id: device_tracker.reynolds_blythe
    to: frontgate
  action:
    service: switch.turn_on
    data:
      entity_id: switch.open_door

- alias: Masterbed Beacon Goodnight
  trigger:
    platform: state
    entity_id: device_tracker.reynolds_darren
    to: masterbed
  condition:
    - condition: state
      entity_id: input_select.house_mode
      state: 'Evening'
  action: # in future make this an actionable nofication to turn off lights
    - service: script.turn_on
      data:
        entity_id: script.bedtime

- alias: Morning Lights
  trigger:
    platform: state
    entity_id: device_tracker.reynolds_darren
    to: kitchen
#  condition:
#    - condition: state
#      entity_id: morning_lights_trigger
#      state: 'off'
  action: # in future make this an actionable nofication to turn off lights
    - service: homeassistant.turn_on
      entity_id: group.morning_lights

#- alias: Masterbed on
#  trigger:
#    platform: state
#    entity_id: device_tracker.reynolds_darren
#    to: masterbed
#  action:
#    service: light.turn_on
#    entity_id: light.study_31

#- alias: Masterbed off
#  trigger:
#    platform: state
#    entity_id: device_tracker.reynolds_darren
#    from: masterbed
#  action:
#    service: light.turn_off
#    entity_id: light.study_31

#- alias: Enter Front Door
#  trigger:
#    platform: zone
#    entity_id: device_tracker.reynolds_darren
#    zone: zone.FrontDoorBeacon
#    # Event is either enter or leave
#    event: enter
#  action:
#    service: light.turn_on
#    entity_id: light.hallway_5
