## Back Deck watering

- alias: Back Deck Watering
  trigger:
    platform: time
    at: '07:30:00'
  condition:
    condition: time
    weekday:
      - tue
      - fri
  action:
    - service: logbook.log
      data_template:
        name: 'Watering:'
        message: Back Deck ON
    - service: notify.ios_darren
      data:
        message: "Back Deck Watering ON"
    - service: switch.turn_on
      entity_id: switch.back_deck_watering_25

- alias: "Back Deck Watering Timer"
  trigger:
    platform: state
    entity_id: switch.back_deck_watering_25
    to: 'on'
  action:
    - delay: '00:{{ states.input_number.backdeck_watering_timer.state | int }}:00'
    - service: switch.turn_off
      entity_id: switch.back_deck_watering_25
    - service: logbook.log
      data_template:
        name: 'Watering:'
        message: Back Deck OFF
