## camera.yaml
- platform: mjpeg
  name: nurserycam
  mjpeg_url: !secret nurserycam_url
  username: !secret nurserycam_uname
  password: !secret nurserycam_pass

- platform: mjpeg
  name: frontcam
  mjpeg_url: !secret frontcam_url
  username: !secret frontcam_uname
  password: !secret frontcam_pass

- platform: doorbird
  last_visitor: true

- platform: bom
  location: Sydney

- platform: generic
  name: BMW X5 Location
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.x5_xdrive30d.attributes.latitude }},{{ states.device_tracker.x5_xdrive30d.attributes.longitude }}&zoom=15&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:X%7C{{ states.device_tracker.x5_xdrive30d.attributes.latitude }},{{ states.device_tracker.x5_xdrive30d.attributes.longitude }}
  #&key={{ !secret google_maps_api_key }}
  limit_refetch_to_url_change: true
  scan_interval: 900
