## camera.yaml
- platform: mjpeg
  name: nurserycam
  mjpeg_url: !secret nurserycam_url
  username: !secret nurserycam_uname
  password: !secret nurserycam_pass

- platform: mjpeg
  name: frontcam
  mjpeg_url: !secret frontcam_url
  username: !secret frontcam_uname
  password: !secret frontcam_pass

- platform: doorbird
  last_visitor: true
