### sensors.yaml
- platform: version
- platform: mqtt
  name: "Darren's Mood"
  state_topic: "home/darren/mood"
  payload_on: "good"
  payload_off: "bad"
  device_class: heat
- platform: plex
  host: !secret plexserver_ip
  username: !secret plexserver_uname
  password: !secret plexserver_pass
- platform: qnap
  host: !secret qnap_ip
  username: !secret qnap_uname
  password: !secret qnap_pass
  monitored_conditions:
    - status
    - cpu_usage
    - memory_percent_used
    - network_tx
    - volume_percentage_used
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: disk_free
      arg: /home
    - type: memory_free
    - type: processor_use
    - type: last_boot
    - type: since_last_boot
    - type: memory_use_percent
    - type: memory_use
    - type: memory_free
    - type: swap_use_percent
    - type: swap_use
    - type: swap_free
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
- platform: speedtest
  server_id: 2629
  monitored_conditions:
    - ping
    - download
    - upload
  minute: 30
  hour:
    - 0
    - 4
    - 8
    - 12
    - 16
    - 20
- platform: google_travel_time
  name: GTDarren_Home
  api_key: !secret google_maps_api_key
  origin: device_tracker.darren
  destination: zone.home
- platform: google_travel_time
  name: GTBlythe_Home
  api_key: !secret google_maps_api_key
  origin: device_tracker.blythe
  destination: zone.home
- platform: google_travel_time
  name: GTHome_Work
  api_key: !secret google_maps_api_key
  origin: zone.home
  destination: zone.work
- platform: google_travel_time
  name: GTHome_City
  api_key: !secret google_maps_api_key
  origin: zone.home
  destination: zone.city
- platform: google_travel_time
  name: GTHome_Thornton
  api_key: !secret google_maps_api_key
  origin: zone.home
  destination: zone.mdn
- platform: google_travel_time
  name: GTHome_Wangi
  api_key: !secret google_maps_api_key
  origin: zone.home
  destination: zone.mdr
- platform: google_travel_time
  name: GTDom_Airport
  api_key: !secret google_maps_api_key
  origin: zone.home
  destination: zone.domairport
- platform: google_travel_time
  name: GTInt_Airport
  api_key: !secret google_maps_api_key
  origin: zone.home
  destination: zone.intairport

## templates
- platform: template
  sensors:
    template_nursery_air_quality:
      friendly_name: "Air Quality"
      unit_of_measurement: "State"
      value_template: "{%if states.sensor.nursery_air_quality.state == '1' %}Good{% elif states.sensor.nursery_air_quality.state == '2' %}Fair{% elif states.sensor.nursery_air_quality.state == '3' %}Poor{% elif states.sensor.nursery_air_quality.state == '4' %}Very Poor{% endif %}"
    template_calendar_family:
      value_template: >
        {{ strptime(states.calendar.family.attributes.start_time, "%Y-%m-%d %H:%M:%S").strftime("%a %I:%M%p") }}:
        {{ states.calendar.family.attributes.message }}
      friendly_name: 'Family'
      unit_of_measurement: ''
## original template for above       {{ strptime(states.calendar.family.attributes.start_time, "%Y-%m-%d %H:%M:%S").strftime("%A, %d of %B, at %H:%M") }}:
    template_gthome_thornton:
      value_template: "{{ states.sensor.gthome_thornton.attributes.duration_in_traffic }}"
      friendly_name: 'Thornton'
      unit_of_measurement: ''
    template_gthome_wangi:
      value_template: "{{ states.sensor.gthome_wangi.attributes.duration_in_traffic }}"
      friendly_name: 'Wangi Wangi'
      unit_of_measurement: ''
- platform: apcupsd
  resources:
    - bcharge
    - linev
    - loadpct
    - nominv
    - nompower
    - numxfers
    - outputv
    - status
    - timeleft
    - tonbatt
